---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.4

inputs:
  - name: dp-dd-job-creator-api-stub
    path: go/src/github.com/ONSdigital/dp-dd-job-creator-api-stub

outputs:
  - name: bin

run:
  path: go/src/github.com/ONSdigital/dp-dd-job-creator-api-stub/ci/scripts/build.sh
